# Generated by Django 4.2.5 on 2023-11-21 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20)),
                ('bedtime', models.TimeField(blank=True, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('total_sleep_duration', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('naps_duration_hour', models.IntegerField(default=0)),
                ('naps_duration_minutes', models.IntegerField(default=0)),
                ('sleep_environment', models.TextField(blank=True)),
                ('pre_sleep_routine', models.TextField(blank=True)),
                ('quality_of_sleep', models.PositiveIntegerField(default=0)),
                ('naps', models.IntegerField(default=0)),
                ('sleep_disturbances', models.TextField(blank=True)),
                ('dreams_or_nightmares', models.TextField(blank=True)),
                ('feeling_upon_waking', models.CharField(blank=True, max_length=50)),
                ('difficulty_falling_asleep', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('difficulty_staying_asleep', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('problems_waking_up_early', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('satisfaction_with_sleep', models.PositiveIntegerField(blank=True, choices=[(0, 'Very Satisfied'), (1, 'Satisfied'), (2, 'Moderately Satisfied'), (3, 'Dissatisfied'), (4, 'Very Dissatisfied')], null=True)),
                ('noticeable_impairment', models.PositiveIntegerField(blank=True, choices=[(0, 'Not at all Noticeable'), (1, 'A Little'), (2, 'Somewhat'), (3, 'Much')], null=True)),
                ('worried_distressed', models.PositiveIntegerField(blank=True, choices=[(0, 'Not at all Worried'), (1, 'A Little'), (2, 'Somewhat'), (3, 'Much'), (4, 'Very Much Worried')], null=True)),
                ('interference_with_daily_functioning', models.PositiveIntegerField(blank=True, choices=[(0, 'Not at all Interfering'), (1, 'A Little'), (2, 'Somewhat'), (3, 'Much'), (4, 'Very Much Interfering')], null=True)),
                ('total_score', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('temperature_file', models.FileField(upload_to='sensor_data/temperature/')),
                ('noise_file', models.FileField(upload_to='sensor_data/noise/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
