# Generated by Django 4.2.5 on 2023-09-17 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('day_of_week', models.CharField(max_length=20)),
                ('bedtime', models.TimeField()),
                ('wake_up_time', models.TimeField()),
                ('total_sleep_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('naps', models.TextField(blank=True, null=True)),
                ('sleep_environment', models.TextField()),
                ('pre_sleep_routine', models.TextField()),
                ('quality_of_sleep', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('sleep_disturbances', models.TextField(blank=True, null=True)),
                ('dreams_or_nightmares', models.TextField(blank=True, null=True)),
                ('feeling_upon_waking', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
