# Generated by Django 4.2.5 on 2023-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepMyth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myth', models.CharField(max_length=200)),
                ('fact', models.TextField()),
            ],
        ),
    ]
